language: node_js
sudo: false
node_js:
  - 10
install:
  - npm i
script:
  - npm test
deploy:
  provider: npm
  email: gautaz@users.noreply.github.com
  api_key:
    secure: qRS0bbic5EWaayvC+/9M/X2UunGkWJbmgYXmfgwBKiCWcqsaTvqN389EVbKRPFfpM/oQN7lqW3O1NpNzQzTzVh2loATszTkstdDa5ksWrO+UB/M/yo76nOXF9+GjQNfMoWSuzbmPZ/Rxx8Or2FR5YW0cd5M6dVZxTMkVXvnaBThATMYVSLle+krxILg56k+RZEENhkdYUxRCNvL+LR22Eqh4MLBJ0nB+hP2PSBJ/sjFhVoR4I442ypnt1ZGt6fs8PUhFTpo9W9OE7QgoEapLxxFBNK1nar00OhVSCd3+qXKcr7UVUh/LNfl0dYd5T55QOw5R180oh0qWPJuM1NC2D73+Tr/1axYYcAahNPDPSi/guLiexLOfjxGa52m0AOXcBiBSIHEluNz1EscbVlHILW2BbfrRSNgYKmrODKDM3r5Di5wYn9t3cx2kQKfKsirJ9TeTOwShHa0+vm5LE3+/hq2sePklJy+a4nZilBtNjRlJUUGUugraVovPd/olhfVclt22CrgYvYx3MY41hoUzmPf2CenFXn0E0JPtCgJ3T5DW0v3qFg48cpf6tXNfeMgtA5xDO1LOKcxyu1R0kjDJwP+tuhllNTLCa/sHXC5oW1EgJ4Db/tAy9zysTK4JPFYPnwsMOwYMSqtAg9heY3pa17vOFIsKs3lwUVkJjZj95tw=
  on:
    tags: true
